// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation-db.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumOp int32

const (
	EnumOp_NULL           EnumOp = 0
	EnumOp_DIVISION       EnumOp = 100
	EnumOp_MULTIPLICATION EnumOp = 200
	EnumOp_SUBTRACTION    EnumOp = 300
	EnumOp_SUM            EnumOp = 400
)

var EnumOp_name = map[int32]string{
	0:   "NULL",
	100: "DIVISION",
	200: "MULTIPLICATION",
	300: "SUBTRACTION",
	400: "SUM",
}

var EnumOp_value = map[string]int32{
	"NULL":           0,
	"DIVISION":       100,
	"MULTIPLICATION": 200,
	"SUBTRACTION":    300,
	"SUM":            400,
}

func (x EnumOp) String() string {
	return proto.EnumName(EnumOp_name, int32(x))
}

func (EnumOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_03edd76800d9572f, []int{0}
}

type OperationDb struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number1              float64  `protobuf:"fixed64,2,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,3,opt,name=number2,proto3" json:"number2,omitempty"`
	Result               float64  `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	Operation            string   `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	DateCreated          string   `protobuf:"bytes,6,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperationDb) Reset()         { *m = OperationDb{} }
func (m *OperationDb) String() string { return proto.CompactTextString(m) }
func (*OperationDb) ProtoMessage()    {}
func (*OperationDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_03edd76800d9572f, []int{0}
}

func (m *OperationDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationDb.Unmarshal(m, b)
}
func (m *OperationDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationDb.Marshal(b, m, deterministic)
}
func (m *OperationDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationDb.Merge(m, src)
}
func (m *OperationDb) XXX_Size() int {
	return xxx_messageInfo_OperationDb.Size(m)
}
func (m *OperationDb) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationDb.DiscardUnknown(m)
}

var xxx_messageInfo_OperationDb proto.InternalMessageInfo

func (m *OperationDb) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OperationDb) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *OperationDb) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

func (m *OperationDb) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *OperationDb) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *OperationDb) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func init() {
	proto.RegisterEnum("EnumOp", EnumOp_name, EnumOp_value)
	proto.RegisterType((*OperationDb)(nil), "OperationDb")
}

func init() {
	proto.RegisterFile("operation-db.proto", fileDescriptor_03edd76800d9572f)
}

var fileDescriptor_03edd76800d9572f = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x4d, 0x49, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x5a,
	0xc9, 0xc8, 0xc5, 0xed, 0x0f, 0x13, 0x76, 0x49, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb2, 0x84, 0x24, 0xb8, 0xd8, 0xf3, 0x4a, 0x73, 0x93, 0x52,
	0x8b, 0x0c, 0x25, 0x98, 0x80, 0x82, 0x8c, 0x41, 0x30, 0x2e, 0x42, 0xc6, 0x48, 0x82, 0x19, 0x59,
	0xc6, 0x48, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x82, 0x05, 0x2c, 0x01,
	0xe5, 0x09, 0xc9, 0x70, 0x71, 0xc2, 0x5d, 0x20, 0xc1, 0x0a, 0xb6, 0x02, 0x21, 0x20, 0xa4, 0xc0,
	0xc5, 0x9d, 0x92, 0x58, 0x92, 0xea, 0x5c, 0x94, 0x0a, 0x24, 0x53, 0x24, 0xd8, 0xc0, 0xf2, 0xc8,
	0x42, 0x5a, 0x81, 0x5c, 0x6c, 0xa9, 0x40, 0x3b, 0xfc, 0x0b, 0x84, 0x38, 0xb8, 0x58, 0xfc, 0x42,
	0x7d, 0x7c, 0x04, 0x18, 0x84, 0x78, 0xb8, 0x38, 0x5c, 0x3c, 0xc3, 0x3c, 0x83, 0x3d, 0xfd, 0xfd,
	0x04, 0x52, 0x84, 0x84, 0xb9, 0xf8, 0x7c, 0x43, 0x7d, 0x42, 0x3c, 0x03, 0x7c, 0x3c, 0x9d, 0x1d,
	0x43, 0x40, 0x62, 0x27, 0x18, 0x85, 0x04, 0xb8, 0xb8, 0x83, 0x43, 0x9d, 0x42, 0x82, 0x1c, 0x9d,
	0xc1, 0x22, 0x6b, 0x98, 0x80, 0xda, 0x99, 0x83, 0x43, 0x7d, 0x05, 0x26, 0x30, 0x3b, 0xb1, 0x47,
	0xb1, 0x82, 0xc3, 0x21, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x67,
	0x34, 0xec, 0x24, 0x01, 0x00, 0x00,
}
