// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation-db-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{0}
}

func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(m, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindByIdResponse struct {
	OperationDb          *OperationDb `protobuf:"bytes,1,opt,name=operationDb,proto3" json:"operationDb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindByIdResponse) Reset()         { *m = FindByIdResponse{} }
func (m *FindByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindByIdResponse) ProtoMessage()    {}
func (*FindByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{1}
}

func (m *FindByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdResponse.Unmarshal(m, b)
}
func (m *FindByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdResponse.Merge(m, src)
}
func (m *FindByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindByIdResponse.Size(m)
}
func (m *FindByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdResponse proto.InternalMessageInfo

func (m *FindByIdResponse) GetOperationDb() *OperationDb {
	if m != nil {
		return m.OperationDb
	}
	return nil
}

type FindByOpRequest struct {
	Op                   EnumOp   `protobuf:"varint,1,opt,name=op,proto3,enum=EnumOp" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByOpRequest) Reset()         { *m = FindByOpRequest{} }
func (m *FindByOpRequest) String() string { return proto.CompactTextString(m) }
func (*FindByOpRequest) ProtoMessage()    {}
func (*FindByOpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{2}
}

func (m *FindByOpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOpRequest.Unmarshal(m, b)
}
func (m *FindByOpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOpRequest.Marshal(b, m, deterministic)
}
func (m *FindByOpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOpRequest.Merge(m, src)
}
func (m *FindByOpRequest) XXX_Size() int {
	return xxx_messageInfo_FindByOpRequest.Size(m)
}
func (m *FindByOpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOpRequest proto.InternalMessageInfo

func (m *FindByOpRequest) GetOp() EnumOp {
	if m != nil {
		return m.Op
	}
	return EnumOp_DIVISION
}

type FindByOpResponse struct {
	OperationDb          *OperationDb `protobuf:"bytes,1,opt,name=operationDb,proto3" json:"operationDb,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindByOpResponse) Reset()         { *m = FindByOpResponse{} }
func (m *FindByOpResponse) String() string { return proto.CompactTextString(m) }
func (*FindByOpResponse) ProtoMessage()    {}
func (*FindByOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{3}
}

func (m *FindByOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOpResponse.Unmarshal(m, b)
}
func (m *FindByOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOpResponse.Marshal(b, m, deterministic)
}
func (m *FindByOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOpResponse.Merge(m, src)
}
func (m *FindByOpResponse) XXX_Size() int {
	return xxx_messageInfo_FindByOpResponse.Size(m)
}
func (m *FindByOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOpResponse proto.InternalMessageInfo

func (m *FindByOpResponse) GetOperationDb() *OperationDb {
	if m != nil {
		return m.OperationDb
	}
	return nil
}

type ListAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllRequest) Reset()         { *m = ListAllRequest{} }
func (m *ListAllRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllRequest) ProtoMessage()    {}
func (*ListAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{4}
}

func (m *ListAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllRequest.Unmarshal(m, b)
}
func (m *ListAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllRequest.Marshal(b, m, deterministic)
}
func (m *ListAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllRequest.Merge(m, src)
}
func (m *ListAllRequest) XXX_Size() int {
	return xxx_messageInfo_ListAllRequest.Size(m)
}
func (m *ListAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllRequest proto.InternalMessageInfo

type ListAllResponse struct {
	Operations           []*OperationDb `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListAllResponse) Reset()         { *m = ListAllResponse{} }
func (m *ListAllResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllResponse) ProtoMessage()    {}
func (*ListAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca76f41c7091e15b, []int{5}
}

func (m *ListAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllResponse.Unmarshal(m, b)
}
func (m *ListAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllResponse.Marshal(b, m, deterministic)
}
func (m *ListAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllResponse.Merge(m, src)
}
func (m *ListAllResponse) XXX_Size() int {
	return xxx_messageInfo_ListAllResponse.Size(m)
}
func (m *ListAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllResponse proto.InternalMessageInfo

func (m *ListAllResponse) GetOperations() []*OperationDb {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*FindByIdRequest)(nil), "FindByIdRequest")
	proto.RegisterType((*FindByIdResponse)(nil), "FindByIdResponse")
	proto.RegisterType((*FindByOpRequest)(nil), "FindByOpRequest")
	proto.RegisterType((*FindByOpResponse)(nil), "FindByOpResponse")
	proto.RegisterType((*ListAllRequest)(nil), "ListAllRequest")
	proto.RegisterType((*ListAllResponse)(nil), "ListAllResponse")
}

func init() {
	proto.RegisterFile("operation-db-service.proto", fileDescriptor_ca76f41c7091e15b)
}

var fileDescriptor_ca76f41c7091e15b = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x51, 0xcf, 0x4a, 0xc3, 0x30,
	0x18, 0xa7, 0x13, 0xad, 0x7e, 0x93, 0xb6, 0xe6, 0xa2, 0xf4, 0xa4, 0x39, 0x89, 0x6c, 0x9f, 0x50,
	0x1f, 0x40, 0x2c, 0x22, 0x08, 0x42, 0xa1, 0xde, 0xbc, 0x59, 0x93, 0x43, 0x60, 0x26, 0xb1, 0xc9,
	0x04, 0xdf, 0xc7, 0x07, 0x35, 0x66, 0x6d, 0x1a, 0xb7, 0x9b, 0xa7, 0x96, 0xdf, 0xdf, 0x7e, 0xbf,
	0x42, 0xa9, 0x34, 0xef, 0x5f, 0xad, 0x50, 0x72, 0xc9, 0xba, 0xa5, 0xe1, 0xfd, 0xa7, 0x78, 0xe3,
	0xa8, 0x7b, 0x65, 0x55, 0x49, 0x62, 0x6e, 0x83, 0xd1, 0x0b, 0xc8, 0x1f, 0x84, 0x64, 0xf5, 0xd7,
	0x23, 0x6b, 0xf9, 0xc7, 0x9a, 0x1b, 0x4b, 0x32, 0x98, 0x09, 0x76, 0x96, 0x9c, 0x27, 0x97, 0x47,
	0xad, 0x7b, 0xa3, 0x35, 0x14, 0x93, 0xc4, 0x68, 0x25, 0x0d, 0x27, 0x08, 0xf3, 0x10, 0x76, 0xdf,
	0x79, 0xf1, 0xbc, 0x3a, 0xc6, 0x66, 0xc2, 0xda, 0x58, 0x40, 0xaf, 0xc6, 0x9a, 0x46, 0x8f, 0x35,
	0xa7, 0x30, 0x53, 0xda, 0x3b, 0xb3, 0x2a, 0x45, 0x2e, 0xd7, 0xef, 0x8e, 0x73, 0xd0, 0xd4, 0xf7,
	0xab, 0xfd, 0x67, 0x5f, 0x01, 0xd9, 0x93, 0x30, 0xf6, 0x6e, 0xb5, 0x1a, 0xea, 0xe8, 0x2d, 0xe4,
	0x01, 0x19, 0x42, 0x17, 0x00, 0xc1, 0x63, 0x5c, 0xe6, 0xde, 0x4e, 0x66, 0xc4, 0x57, 0xdf, 0x09,
	0x90, 0x88, 0x7b, 0xde, 0x4c, 0x4b, 0xae, 0xe1, 0x70, 0x5c, 0x87, 0x14, 0xb8, 0xb5, 0x65, 0x79,
	0x82, 0x3b, 0xd3, 0x05, 0x43, 0xa3, 0x83, 0x21, 0xac, 0x12, 0x0c, 0xd1, 0xed, 0x0b, 0x48, 0x87,
	0x2f, 0x27, 0x39, 0xfe, 0xbd, 0xaa, 0x2c, 0x70, 0xeb, 0xa8, 0x3a, 0x7d, 0xd9, 0xf7, 0x7f, 0xb6,
	0x3b, 0xf0, 0x8f, 0x9b, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x19, 0xc6, 0xd9, 0x12, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OperationDbServiceClient is the client API for OperationDbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperationDbServiceClient interface {
	FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error)
	FindByOp(ctx context.Context, in *FindByOpRequest, opts ...grpc.CallOption) (*FindByOpResponse, error)
	ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error)
}

type operationDbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationDbServiceClient(cc grpc.ClientConnInterface) OperationDbServiceClient {
	return &operationDbServiceClient{cc}
}

func (c *operationDbServiceClient) FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error) {
	out := new(FindByIdResponse)
	err := c.cc.Invoke(ctx, "/OperationDbService/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationDbServiceClient) FindByOp(ctx context.Context, in *FindByOpRequest, opts ...grpc.CallOption) (*FindByOpResponse, error) {
	out := new(FindByOpResponse)
	err := c.cc.Invoke(ctx, "/OperationDbService/FindByOp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationDbServiceClient) ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error) {
	out := new(ListAllResponse)
	err := c.cc.Invoke(ctx, "/OperationDbService/ListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationDbServiceServer is the server API for OperationDbService service.
type OperationDbServiceServer interface {
	FindById(context.Context, *FindByIdRequest) (*FindByIdResponse, error)
	FindByOp(context.Context, *FindByOpRequest) (*FindByOpResponse, error)
	ListAll(context.Context, *ListAllRequest) (*ListAllResponse, error)
}

// UnimplementedOperationDbServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOperationDbServiceServer struct {
}

func (*UnimplementedOperationDbServiceServer) FindById(ctx context.Context, req *FindByIdRequest) (*FindByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (*UnimplementedOperationDbServiceServer) FindByOp(ctx context.Context, req *FindByOpRequest) (*FindByOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByOp not implemented")
}
func (*UnimplementedOperationDbServiceServer) ListAll(ctx context.Context, req *ListAllRequest) (*ListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}

func RegisterOperationDbServiceServer(s *grpc.Server, srv OperationDbServiceServer) {
	s.RegisterService(&_OperationDbService_serviceDesc, srv)
}

func _OperationDbService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationDbServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationDbService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationDbServiceServer).FindById(ctx, req.(*FindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationDbService_FindByOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationDbServiceServer).FindByOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationDbService/FindByOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationDbServiceServer).FindByOp(ctx, req.(*FindByOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationDbService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationDbServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationDbService/ListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationDbServiceServer).ListAll(ctx, req.(*ListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OperationDbService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OperationDbService",
	HandlerType: (*OperationDbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindById",
			Handler:    _OperationDbService_FindById_Handler,
		},
		{
			MethodName: "FindByOp",
			Handler:    _OperationDbService_FindByOp_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _OperationDbService_ListAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation-db-service.proto",
}
