// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation-service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	Number1              float64  `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *SumRequest) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type SumResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MultiplicationRequest struct {
	Number1              float64  `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplicationRequest) Reset()         { *m = MultiplicationRequest{} }
func (m *MultiplicationRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplicationRequest) ProtoMessage()    {}
func (*MultiplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{2}
}

func (m *MultiplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplicationRequest.Unmarshal(m, b)
}
func (m *MultiplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplicationRequest.Marshal(b, m, deterministic)
}
func (m *MultiplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplicationRequest.Merge(m, src)
}
func (m *MultiplicationRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplicationRequest.Size(m)
}
func (m *MultiplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplicationRequest proto.InternalMessageInfo

func (m *MultiplicationRequest) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *MultiplicationRequest) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type MultiplicationResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplicationResponse) Reset()         { *m = MultiplicationResponse{} }
func (m *MultiplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplicationResponse) ProtoMessage()    {}
func (*MultiplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{3}
}

func (m *MultiplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplicationResponse.Unmarshal(m, b)
}
func (m *MultiplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplicationResponse.Marshal(b, m, deterministic)
}
func (m *MultiplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplicationResponse.Merge(m, src)
}
func (m *MultiplicationResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplicationResponse.Size(m)
}
func (m *MultiplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplicationResponse proto.InternalMessageInfo

func (m *MultiplicationResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type DivisionRequest struct {
	Number1              float64  `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivisionRequest) Reset()         { *m = DivisionRequest{} }
func (m *DivisionRequest) String() string { return proto.CompactTextString(m) }
func (*DivisionRequest) ProtoMessage()    {}
func (*DivisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{4}
}

func (m *DivisionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivisionRequest.Unmarshal(m, b)
}
func (m *DivisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivisionRequest.Marshal(b, m, deterministic)
}
func (m *DivisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivisionRequest.Merge(m, src)
}
func (m *DivisionRequest) XXX_Size() int {
	return xxx_messageInfo_DivisionRequest.Size(m)
}
func (m *DivisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DivisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DivisionRequest proto.InternalMessageInfo

func (m *DivisionRequest) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *DivisionRequest) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type DivisionResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivisionResponse) Reset()         { *m = DivisionResponse{} }
func (m *DivisionResponse) String() string { return proto.CompactTextString(m) }
func (*DivisionResponse) ProtoMessage()    {}
func (*DivisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{5}
}

func (m *DivisionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivisionResponse.Unmarshal(m, b)
}
func (m *DivisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivisionResponse.Marshal(b, m, deterministic)
}
func (m *DivisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivisionResponse.Merge(m, src)
}
func (m *DivisionResponse) XXX_Size() int {
	return xxx_messageInfo_DivisionResponse.Size(m)
}
func (m *DivisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DivisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DivisionResponse proto.InternalMessageInfo

func (m *DivisionResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SubtractionRequest struct {
	Number1              float64  `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubtractionRequest) Reset()         { *m = SubtractionRequest{} }
func (m *SubtractionRequest) String() string { return proto.CompactTextString(m) }
func (*SubtractionRequest) ProtoMessage()    {}
func (*SubtractionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{6}
}

func (m *SubtractionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubtractionRequest.Unmarshal(m, b)
}
func (m *SubtractionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubtractionRequest.Marshal(b, m, deterministic)
}
func (m *SubtractionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubtractionRequest.Merge(m, src)
}
func (m *SubtractionRequest) XXX_Size() int {
	return xxx_messageInfo_SubtractionRequest.Size(m)
}
func (m *SubtractionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubtractionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubtractionRequest proto.InternalMessageInfo

func (m *SubtractionRequest) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *SubtractionRequest) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

type SubtractionResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubtractionResponse) Reset()         { *m = SubtractionResponse{} }
func (m *SubtractionResponse) String() string { return proto.CompactTextString(m) }
func (*SubtractionResponse) ProtoMessage()    {}
func (*SubtractionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{7}
}

func (m *SubtractionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubtractionResponse.Unmarshal(m, b)
}
func (m *SubtractionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubtractionResponse.Marshal(b, m, deterministic)
}
func (m *SubtractionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubtractionResponse.Merge(m, src)
}
func (m *SubtractionResponse) XXX_Size() int {
	return xxx_messageInfo_SubtractionResponse.Size(m)
}
func (m *SubtractionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubtractionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubtractionResponse proto.InternalMessageInfo

func (m *SubtractionResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type FindByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByIdRequest) Reset()         { *m = FindByIdRequest{} }
func (m *FindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindByIdRequest) ProtoMessage()    {}
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{8}
}

func (m *FindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdRequest.Unmarshal(m, b)
}
func (m *FindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdRequest.Marshal(b, m, deterministic)
}
func (m *FindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdRequest.Merge(m, src)
}
func (m *FindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindByIdRequest.Size(m)
}
func (m *FindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdRequest proto.InternalMessageInfo

func (m *FindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindByIdResponse struct {
	Operation            *Operation `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindByIdResponse) Reset()         { *m = FindByIdResponse{} }
func (m *FindByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FindByIdResponse) ProtoMessage()    {}
func (*FindByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{9}
}

func (m *FindByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIdResponse.Unmarshal(m, b)
}
func (m *FindByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIdResponse.Marshal(b, m, deterministic)
}
func (m *FindByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIdResponse.Merge(m, src)
}
func (m *FindByIdResponse) XXX_Size() int {
	return xxx_messageInfo_FindByIdResponse.Size(m)
}
func (m *FindByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIdResponse proto.InternalMessageInfo

func (m *FindByIdResponse) GetOperation() *Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type FindByOpRequest struct {
	Op                   EnumOp   `protobuf:"varint,1,opt,name=op,proto3,enum=EnumOp" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByOpRequest) Reset()         { *m = FindByOpRequest{} }
func (m *FindByOpRequest) String() string { return proto.CompactTextString(m) }
func (*FindByOpRequest) ProtoMessage()    {}
func (*FindByOpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{10}
}

func (m *FindByOpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOpRequest.Unmarshal(m, b)
}
func (m *FindByOpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOpRequest.Marshal(b, m, deterministic)
}
func (m *FindByOpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOpRequest.Merge(m, src)
}
func (m *FindByOpRequest) XXX_Size() int {
	return xxx_messageInfo_FindByOpRequest.Size(m)
}
func (m *FindByOpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOpRequest proto.InternalMessageInfo

func (m *FindByOpRequest) GetOp() EnumOp {
	if m != nil {
		return m.Op
	}
	return EnumOp_NULL
}

type FindByOpResponse struct {
	Operations           []*Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindByOpResponse) Reset()         { *m = FindByOpResponse{} }
func (m *FindByOpResponse) String() string { return proto.CompactTextString(m) }
func (*FindByOpResponse) ProtoMessage()    {}
func (*FindByOpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{11}
}

func (m *FindByOpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByOpResponse.Unmarshal(m, b)
}
func (m *FindByOpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByOpResponse.Marshal(b, m, deterministic)
}
func (m *FindByOpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByOpResponse.Merge(m, src)
}
func (m *FindByOpResponse) XXX_Size() int {
	return xxx_messageInfo_FindByOpResponse.Size(m)
}
func (m *FindByOpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByOpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindByOpResponse proto.InternalMessageInfo

func (m *FindByOpResponse) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type ListAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAllRequest) Reset()         { *m = ListAllRequest{} }
func (m *ListAllRequest) String() string { return proto.CompactTextString(m) }
func (*ListAllRequest) ProtoMessage()    {}
func (*ListAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{12}
}

func (m *ListAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllRequest.Unmarshal(m, b)
}
func (m *ListAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllRequest.Marshal(b, m, deterministic)
}
func (m *ListAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllRequest.Merge(m, src)
}
func (m *ListAllRequest) XXX_Size() int {
	return xxx_messageInfo_ListAllRequest.Size(m)
}
func (m *ListAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllRequest proto.InternalMessageInfo

type ListAllResponse struct {
	Operations           []*Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListAllResponse) Reset()         { *m = ListAllResponse{} }
func (m *ListAllResponse) String() string { return proto.CompactTextString(m) }
func (*ListAllResponse) ProtoMessage()    {}
func (*ListAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ecdeba5886db1db, []int{13}
}

func (m *ListAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAllResponse.Unmarshal(m, b)
}
func (m *ListAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAllResponse.Marshal(b, m, deterministic)
}
func (m *ListAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAllResponse.Merge(m, src)
}
func (m *ListAllResponse) XXX_Size() int {
	return xxx_messageInfo_ListAllResponse.Size(m)
}
func (m *ListAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAllResponse proto.InternalMessageInfo

func (m *ListAllResponse) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "SumRequest")
	proto.RegisterType((*SumResponse)(nil), "SumResponse")
	proto.RegisterType((*MultiplicationRequest)(nil), "MultiplicationRequest")
	proto.RegisterType((*MultiplicationResponse)(nil), "MultiplicationResponse")
	proto.RegisterType((*DivisionRequest)(nil), "DivisionRequest")
	proto.RegisterType((*DivisionResponse)(nil), "DivisionResponse")
	proto.RegisterType((*SubtractionRequest)(nil), "SubtractionRequest")
	proto.RegisterType((*SubtractionResponse)(nil), "SubtractionResponse")
	proto.RegisterType((*FindByIdRequest)(nil), "FindByIdRequest")
	proto.RegisterType((*FindByIdResponse)(nil), "FindByIdResponse")
	proto.RegisterType((*FindByOpRequest)(nil), "FindByOpRequest")
	proto.RegisterType((*FindByOpResponse)(nil), "FindByOpResponse")
	proto.RegisterType((*ListAllRequest)(nil), "ListAllRequest")
	proto.RegisterType((*ListAllResponse)(nil), "ListAllResponse")
}

func init() {
	proto.RegisterFile("operation-service.proto", fileDescriptor_3ecdeba5886db1db)
}

var fileDescriptor_3ecdeba5886db1db = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xcd, 0x4e, 0xf2, 0x40,
	0x18, 0x85, 0x43, 0xc9, 0x47, 0x3f, 0x5e, 0x4c, 0x5b, 0x07, 0x05, 0xd2, 0x15, 0x36, 0x31, 0x21,
	0x44, 0x46, 0xad, 0x1b, 0x17, 0x6a, 0x84, 0xa8, 0xd1, 0xa8, 0x21, 0x29, 0x3b, 0x77, 0xfc, 0xcc,
	0x62, 0x92, 0xd2, 0xd6, 0x4e, 0x4b, 0xe2, 0x6d, 0x7b, 0x05, 0x0e, 0xa5, 0x33, 0x2d, 0x05, 0x43,
	0x0c, 0xab, 0xd2, 0xf7, 0xe7, 0x3c, 0x03, 0xe7, 0x0c, 0xd0, 0xf4, 0x03, 0x12, 0x8e, 0x23, 0xea,
	0x7b, 0x3d, 0x46, 0xc2, 0x05, 0x9d, 0x12, 0x1c, 0x84, 0x7e, 0xe4, 0x9b, 0xba, 0x6c, 0xac, 0x0a,
	0xd6, 0x3d, 0xc0, 0x28, 0x9e, 0x3b, 0xe4, 0x33, 0x26, 0x2c, 0x42, 0x2d, 0x50, 0xbd, 0x78, 0x3e,
	0x21, 0xe1, 0x65, 0xab, 0xd4, 0x2e, 0x75, 0x4a, 0x8e, 0x78, 0xcd, 0x3a, 0x76, 0x4b, 0xc9, 0x77,
	0x6c, 0xeb, 0x14, 0x6a, 0x89, 0x02, 0x0b, 0x7c, 0x8f, 0x11, 0xd4, 0x80, 0x4a, 0x48, 0x58, 0xec,
	0x46, 0xa9, 0x42, 0xfa, 0x66, 0xbd, 0xc2, 0xf1, 0x3b, 0x7f, 0xd2, 0xc0, 0xa5, 0xd3, 0xe4, 0x00,
	0xfb, 0x30, 0x2f, 0xa0, 0x51, 0x14, 0xdb, 0x81, 0x7f, 0x04, 0xfd, 0x81, 0x2e, 0x28, 0xdb, 0x13,
	0xdc, 0x05, 0x23, 0x93, 0xd9, 0x81, 0x7c, 0x06, 0x34, 0x8a, 0x27, 0x51, 0x38, 0x9e, 0xee, 0xfb,
	0x75, 0x7b, 0x50, 0x5f, 0x53, 0xda, 0x01, 0x3e, 0x01, 0xfd, 0x89, 0x7a, 0xb3, 0xc1, 0xd7, 0xcb,
	0x4c, 0x50, 0x35, 0x50, 0xe8, 0x2c, 0x19, 0xab, 0x3a, 0xfc, 0x93, 0x75, 0x03, 0x46, 0x36, 0x92,
	0xca, 0x75, 0xa0, 0x2a, 0xd3, 0x91, 0x8c, 0xd6, 0x6c, 0xc0, 0x43, 0x51, 0x71, 0xb2, 0x26, 0xff,
	0x15, 0x52, 0xc0, 0x30, 0x10, 0x80, 0x26, 0x28, 0x7e, 0x90, 0x6c, 0x69, 0xb6, 0x8a, 0x09, 0x3f,
	0x39, 0xef, 0xf1, 0x92, 0x75, 0x27, 0x48, 0xcb, 0xd9, 0x94, 0xd4, 0x05, 0x90, 0x62, 0x8c, 0x2f,
	0x95, 0x0b, 0xa8, 0x5c, 0xd7, 0x32, 0x40, 0x7b, 0xa3, 0x2c, 0xea, 0xbb, 0x6e, 0x8a, 0xb2, 0x6e,
	0x41, 0x97, 0x95, 0xbf, 0x0b, 0xda, 0xdf, 0x0a, 0x18, 0xb2, 0x33, 0x5a, 0xdd, 0x0e, 0xd4, 0x86,
	0x32, 0x0f, 0x31, 0xaa, 0xe1, 0xec, 0x32, 0x98, 0x07, 0x38, 0x9f, 0xeb, 0x3e, 0x68, 0xeb, 0x91,
	0x43, 0x0d, 0xbc, 0x35, 0xd0, 0x66, 0x13, 0xff, 0x92, 0xcd, 0x73, 0xf8, 0x2f, 0xc2, 0x83, 0x0c,
	0x5c, 0x88, 0xa3, 0x79, 0x88, 0x37, 0x92, 0x75, 0xbd, 0xbc, 0x5a, 0xd2, 0x77, 0x54, 0xc7, 0x9b,
	0x79, 0x32, 0x8f, 0xf0, 0xb6, 0x68, 0x70, 0x94, 0xf0, 0x97, 0xa3, 0x0a, 0x69, 0xe0, 0xa8, 0x0d,
	0xf3, 0xe5, 0xc2, 0x30, 0x90, 0x0b, 0xd2, 0x5d, 0xb9, 0x90, 0xf3, 0xf0, 0x0c, 0xd4, 0xd4, 0x05,
	0xa4, 0xe3, 0x75, 0x87, 0x4c, 0x03, 0x17, 0x0c, 0x1a, 0xa8, 0x1f, 0xff, 0x92, 0xff, 0x9b, 0x49,
	0x25, 0x79, 0x5c, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe9, 0x8d, 0xc0, 0xa2, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OperationServiceClient is the client API for OperationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperationServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	Multiplication(ctx context.Context, in *MultiplicationRequest, opts ...grpc.CallOption) (*MultiplicationResponse, error)
	Division(ctx context.Context, in *DivisionRequest, opts ...grpc.CallOption) (*DivisionResponse, error)
	Subtraction(ctx context.Context, in *SubtractionRequest, opts ...grpc.CallOption) (*SubtractionResponse, error)
	FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error)
	FindByOp(ctx context.Context, in *FindByOpRequest, opts ...grpc.CallOption) (*FindByOpResponse, error)
	ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error)
}

type operationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationServiceClient(cc grpc.ClientConnInterface) OperationServiceClient {
	return &operationServiceClient{cc}
}

func (c *operationServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/OperationService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) Multiplication(ctx context.Context, in *MultiplicationRequest, opts ...grpc.CallOption) (*MultiplicationResponse, error) {
	out := new(MultiplicationResponse)
	err := c.cc.Invoke(ctx, "/OperationService/Multiplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) Division(ctx context.Context, in *DivisionRequest, opts ...grpc.CallOption) (*DivisionResponse, error) {
	out := new(DivisionResponse)
	err := c.cc.Invoke(ctx, "/OperationService/Division", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) Subtraction(ctx context.Context, in *SubtractionRequest, opts ...grpc.CallOption) (*SubtractionResponse, error) {
	out := new(SubtractionResponse)
	err := c.cc.Invoke(ctx, "/OperationService/Subtraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) FindById(ctx context.Context, in *FindByIdRequest, opts ...grpc.CallOption) (*FindByIdResponse, error) {
	out := new(FindByIdResponse)
	err := c.cc.Invoke(ctx, "/OperationService/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) FindByOp(ctx context.Context, in *FindByOpRequest, opts ...grpc.CallOption) (*FindByOpResponse, error) {
	out := new(FindByOpResponse)
	err := c.cc.Invoke(ctx, "/OperationService/FindByOp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationServiceClient) ListAll(ctx context.Context, in *ListAllRequest, opts ...grpc.CallOption) (*ListAllResponse, error) {
	out := new(ListAllResponse)
	err := c.cc.Invoke(ctx, "/OperationService/ListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationServiceServer is the server API for OperationService service.
type OperationServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	Multiplication(context.Context, *MultiplicationRequest) (*MultiplicationResponse, error)
	Division(context.Context, *DivisionRequest) (*DivisionResponse, error)
	Subtraction(context.Context, *SubtractionRequest) (*SubtractionResponse, error)
	FindById(context.Context, *FindByIdRequest) (*FindByIdResponse, error)
	FindByOp(context.Context, *FindByOpRequest) (*FindByOpResponse, error)
	ListAll(context.Context, *ListAllRequest) (*ListAllResponse, error)
}

// UnimplementedOperationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOperationServiceServer struct {
}

func (*UnimplementedOperationServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedOperationServiceServer) Multiplication(ctx context.Context, req *MultiplicationRequest) (*MultiplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiplication not implemented")
}
func (*UnimplementedOperationServiceServer) Division(ctx context.Context, req *DivisionRequest) (*DivisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Division not implemented")
}
func (*UnimplementedOperationServiceServer) Subtraction(ctx context.Context, req *SubtractionRequest) (*SubtractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subtraction not implemented")
}
func (*UnimplementedOperationServiceServer) FindById(ctx context.Context, req *FindByIdRequest) (*FindByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (*UnimplementedOperationServiceServer) FindByOp(ctx context.Context, req *FindByOpRequest) (*FindByOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByOp not implemented")
}
func (*UnimplementedOperationServiceServer) ListAll(ctx context.Context, req *ListAllRequest) (*ListAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}

func RegisterOperationServiceServer(s *grpc.Server, srv OperationServiceServer) {
	s.RegisterService(&_OperationService_serviceDesc, srv)
}

func _OperationService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_Multiplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Multiplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/Multiplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Multiplication(ctx, req.(*MultiplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_Division_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Division(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/Division",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Division(ctx, req.(*DivisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_Subtraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).Subtraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/Subtraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).Subtraction(ctx, req.(*SubtractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).FindById(ctx, req.(*FindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_FindByOp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).FindByOp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/FindByOp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).FindByOp(ctx, req.(*FindByOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OperationService/ListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationServiceServer).ListAll(ctx, req.(*ListAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OperationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OperationService",
	HandlerType: (*OperationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _OperationService_Sum_Handler,
		},
		{
			MethodName: "Multiplication",
			Handler:    _OperationService_Multiplication_Handler,
		},
		{
			MethodName: "Division",
			Handler:    _OperationService_Division_Handler,
		},
		{
			MethodName: "Subtraction",
			Handler:    _OperationService_Subtraction_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _OperationService_FindById_Handler,
		},
		{
			MethodName: "FindByOp",
			Handler:    _OperationService_FindByOp_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _OperationService_ListAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation-service.proto",
}
