// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operation.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation struct {
	Number1              float64  `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2              float64  `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_619dee0fded31cb3, []int{0}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetNumber1() float64 {
	if m != nil {
		return m.Number1
	}
	return 0
}

func (m *Operation) GetNumber2() float64 {
	if m != nil {
		return m.Number2
	}
	return 0
}

func init() {
	proto.RegisterType((*Operation)(nil), "Operation")
}

func init() {
	proto.RegisterFile("operation.proto", fileDescriptor_619dee0fded31cb3)
}

var fileDescriptor_619dee0fded31cb3 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe7, 0xe2, 0xf4,
	0x87, 0x09, 0x09, 0x49, 0x70, 0xb1, 0xe7, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x19, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x30, 0x06, 0xc1, 0xb8, 0x08, 0x19, 0x23, 0x09, 0x26, 0x64, 0x19, 0x23, 0x27, 0xf6,
	0x28, 0x56, 0xb0, 0x49, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x82, 0xd8,
	0x30, 0xe7, 0x63, 0x00, 0x00, 0x00,
}
